version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "monthly"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/backend"
    schedule:
      interval: "monthly"
