[project]
name = "ilmanlaatu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "httpx[http2,zstd]>=0.28.1",
    "pendulum>=3.1.0",
    "polars>=1.34.0",
    "rich>=14.2.0",
]
