

GET https://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi::observations::airquality::hourly::simple HTTP/1.1

###

GET https://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi::observations::airquality::hourly::multipointcoverage HTTP/1.1

###

GET https://opendata.fmi.fi/wfs?service=WFS&request=getFeature&storedquery_id=fmi::observations::airquality::hourly::timevaluepair HTTP/1.1

###

GET https://opendata.fmi.fi/wfs?service=WFS&request=GetCapabilities HTTP/1.1
